### ISSUE TITLE
Disqus template

### ISSUE THREAD

**Issue by damccull** [ejmg/zerm#22]
I see there's a 'comments.html' macro available. How would someone go about putting a disqus snippet in there properly with your template?

Thanks.

**Comment by ejmg** [comment]
Ah, for a moment I completely forgot I even made that file.

So, as it exists, that's just a stub for templating code. In theory, all you need to do is add whatever snippet of code Disqus gives you for adding their comment widget into that macro block. Then you would need to add that macro's invocation into the templates you would want to have comments on. It looks like I anticipated that to be somewhere around [here in page.html](https://github.com/ejmg/zerm/blob/b316f904dcbe60a255beec68e6c23436c1d11f07/templates/page.html#L22-L23).

Caveats:
- Styling isn't set at all for this, so you may need to do some tweaking here to make it not break things or look horrendous
- I presume there is some JS needed for this (I've never used/looked at Disqus directly). For my trivial solution above, it would need to be inlined in the HTML you paste into `comments.html`; otherwise, you would want to throw it with the [js assets](https://github.com/ejmg/zerm/tree/master/static/assets/js) and call it as I do for the [menu script here](https://github.com/ejmg/zerm/blob/b316f904dcbe60a255beec68e6c23436c1d11f07/templates/macros/footer.html#L12-L14).

if you put this together, feel free to throw up the changes into a PR :slightly_smiling_face:. you would just want to make sure the config file has a parameter that enables this functionality somehow and then put a small logic check in the templating.

**Comment by damccull** [comment]
I'll try to work it out. I'm not yet familiar enough with Zola or your template to understand how it works yet, so I'll have to start learning and digging. I just switched over to zola from Wyam (a dotnet generator) because Wyam got replaced by a commercial solution.

If I can figure this out, I'll add it to the template base and send a PR.

**Comment by ejmg** [comment]
Understandable. If have questions or need some help, just let me know.

**Comment by damccull** [comment]
Any chance this will get merged?

**Comment by ejmg** [comment]
Yes, I plan on getting around to the 8 or so outstanding PRs on this theme
soon, probably this weekend.

**Comment by ejmg** [comment]
once the PR conflict is resolved for #27, this issue will be solved thanks to @damccull  :partying_face:
