### ISSUE TITLE
Menu link to external site

### ISSUE THREAD

**Issue by mthld** [ejmg/zerm#23]
Hello,

I would like to know how to create a link to an external site in the menu, looked at the sample configuration files but I can't find a way. `$BASE_URL` always prepend...

Thanks in advance!

**Comment by damccull** [comment]
I think you'd have to edit the template itself. Create a new file your own 'templates' folder with the same path and name as the file in the theme's template folder. That will override the one in the theme. Then you can copy and paste the theme's code into your file, and make whatever mods you want without affecting the theme.

**Comment by mthld** [comment]
Not an ideal solution but it works indeed. Thanks!

**Comment by ejmg** [comment]
Glad this got figured out.

As it functions, yes, `$BASE_URL` will always prepend. Extending themes as @damccull is typically the go-to way for these sort of tweaks, so I'm sorry if that turned into an issue.

The only way I can think of adding arbitrary links in a not-too-annoying-way for users would be to add another parameter in the config file for arbitrary URLs and then extending the existing menu template logic to check if that list is non-empty and, if so, add them to the menu. I say this because I think the existing logic of prepending the $BASE_URL is desired behavior for most people, e.g. creating an ABOUT page, yes?

I think this would be a easy feature to bang out if anyone wants to take a quick swing at it; I'm behind on some of the PRs because of vacation but will be revisiting them soon.
