### ISSUE TITLE
list_pages macros references non-existent paginator.pages

### ISSUE THREAD

**Issue by Phrohdoh** [ejmg/zerm#7]
[index.html](https://github.com/ejmg/zerm/blob/5ca1968a1a88660aa23c8dc51bc9994bb9fdfceb/templates/index.html#L62)'s `main` block invokes the [`list_pages` macro](https://github.com/ejmg/zerm/blob/5ca1968a1a88660aa23c8dc51bc9994bb9fdfceb/templates/macros/lists.html#L1) which references [`paginator.pages`](https://github.com/ejmg/zerm/blob/5ca1968a1a88660aa23c8dc51bc9994bb9fdfceb/templates/macros/lists.html#L4) which, out of the box, does not seem to exist:

```
$ zola serve
Error: Failed to render section 'content/_index.md'
Reason: Failed to render 'index.html': error while rendering macro `lists::list_pages`
Reason: Variable `paginator.pages` not found in context while rendering 'macros/lists.html'
```

I am using zola 0.12.2 and zerm `5ca1968a1a88660aa23c8dc51bc9994bb9fdfceb`.

Is this a zerm issue or did I miss a required configuration option (or global(?) frontmatter)?

**Comment by ejmg** [comment]
How are you using the theme? You shouldn't be getting macro errors with
standard usage. A config file, or access to the site repo, would probably
clarify the issue.

**Comment by Phrohdoh** [comment]
The theme is cloned into the `themes` directory of my zola site's source, as recommend by zola docs.

**Comment by ejmg** [comment]
what is the contents of `_index.md` given that is where the error is originating.

i don't know what changes are introduced by zola `0.12.*`, so there's also a good chance something may have broke wrt internal API and how it's exposed.

**Comment by Phrohdoh** [comment]
The contents of `content/_index.md` is as follows.

```
+++
title = "home"
path  = "$BASE_URL"
+++

todo
```

**Comment by ejmg** [comment]
it's been a while since i've mucked around with zola but, absent a breaking change introduced by `0.12.*`, i think i know what is up.

i should have asked, before anything else, it looks like you are not following the structure of the example content of the zerm theme and that's causing issues. you can see how the [deployed website](zerm.ejmg.now.sh/) is setup under [`content`](https://github.com/ejmg/zerm/tree/master/content). you will immediately note that `content/_index.md` has:
```
+++
sort_by = "date"
transparent = false
paginate_by = 3
+++
```
this is because we don't want _index.md to actually be rendered, we want to use different content to populate the blog at various locations, `/` included. you aren't paginating anything as of now and say as much in your `_index` and that's (probably) why my theme can't find whatever you are pointing it at.

looking at the example site, for things like "pages", e.g. `about`, they have their own directories with an `_index.md`. for `about`, this has:
```
+++
title = "about"
path = "about"

[extra]
date = 2019-03-21
+++

Yet another theme for yet another static site generator; that said, I hope you
like it.
```

for the demo blog itself, individual blog posts are slightly different; while under their own directory, e.g. the `demo` blog post, they have an `index.md` instead. for the `demo` blogpost, the top portion of the file that configures contains:
```
+++
title="demo"
description="a basic demo of zola."
date=2019-08-06

[taxonomies]
tags = ["demo", "zola", "highlighting"]
categories = ["programming", "wu tang",]

[extra]
+++

Here's a general demo of Zola and how things look with zerm.

# Header I

Inline code: `println!("Wu Tang!");`
<!-- snip --!>
```
let me know if that fixes the issue.

if you want to see a slightly different way to arrange your blog, [my own blog might help](https://github.com/ejmg/ageof.info/tree/master/site/content) along with the zola docs proper.

**Comment by Phrohdoh** [comment]
Thank you!! I now have pages rendering (and listed on the site's index).
You absolutely rock.  Also thank you for zerm. :-)

**Comment by ejmg** [comment]
glad to hear it worked out :slightly_smiling_face:
